name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Prepare deployment directory
        run: |
          echo "Preparing static files for deployment..."
          mkdir -p docs
          
          # Copy all markdown files
          cp -r *.md docs/
          cp -r part* docs/ 2>/dev/null || true
          cp -r appendix docs/ 2>/dev/null || true
          cp -r assets docs/ 2>/dev/null || true
          
          # Copy HTML and JSON files
          cp index.html docs/index.html
          cp book.json docs/book.json 2>/dev/null || true
          cp package.json docs/package.json 2>/dev/null || true
          
          # Copy .nojekyll to prevent Jekyll processing
          cp .nojekyll docs/.nojekyll 2>/dev/null || true
          
          echo "Files prepared for deployment:"
          ls -la docs/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4