name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          
      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli@2.3.2
          gitbook fetch 3.2.3
          gitbook --version || echo "GitBook CLI installed"
          
      - name: Install GitBook plugins
        run: |
          gitbook install || echo "No plugins to install"
          
      - name: Build GitBook
        run: |
          gitbook build . ./docs || echo "GitBook build failed, using fallback"
          # 如果GitBook构建失败，复制源文件作为备份
          if [ ! -d "./docs" ]; then
            echo "GitBook build failed, copying source files..."
            mkdir -p docs
            cp -r *.md docs/
            cp -r part* docs/ 2>/dev/null || true
            cp -r appendix docs/ 2>/dev/null || true
            cp -r assets docs/ 2>/dev/null || true
            cp index.html docs/index.html
          fi
          # 确保有index.html
          if [ ! -f "./docs/index.html" ]; then
            cp index.html docs/index.html 2>/dev/null || echo "No index.html to copy"
          fi
          ls -la docs/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4